### PR TITLE
Pull Request to Fix Erlang and Compile Errors

### PR DESCRIPTION
**Pull request by ccoughenour08**
**Overview**
This is a pull request to fix the Erlang download location, and the topologies download issue.

**Fixes**
Most of the work was done in the bin/cfn file and the lib/example/application.ex files.

**Notes**
@clecodes was responsible for getting the topologies fix, while I was troubleshooting the pipeline setup.

### CODE REVIEW

**Comment by bitwalker** [comment]
There are a handful of unrelated changes in here, which I started to unwind - but I'd like to know more about what they were intended to fix before I go further (i.e. the removal of `:logger`).

**Comment by bitwalker** [comment]
I believe this PR has been mostly superceded by #14, but let me know if that is not the case.

**Comment by ccoughenour08** [comment]
Hey Paul, I apologize. These are for debugging another issue in the
codebase. In my initial PR, I resolved the application.ex issue. This
allowed the pipeline to be created. Once you get through that (and the
erlang location issue), the code fails to deploy due to the debugger
configuration. I’ll get this codebase back before that debugging and notify
you.

If you could have a look at that deploy issue, that would be fantastic.

Thanks,
C Luke Coughenour

**Comment by bitwalker** [comment]
No worries! I think #14 takes care of the compilation issues and general "outdatedness" of the Elixir application itself.

> the code fails to deploy due to the debugger configuration. 

Could you clarify this a bit? I don't see an issue outlining any problems with debugging specifically, but I may have missed something in a comment somewhere. An error message or just general description of what fails would help.

If you could, when you get a chance, give things a shot again now that #14 has been merged - it contains a variety of small fixes and updates that may solve the problems you were seeing. If you are still seeing issues, then we will at least have an updated set of issues which we can iterate on.

**Comment by ccoughenour08** [comment]
Again sorry! Writing this on mobile. It was a logger** issue. I’ll get the
stack out here this evening!

Thanks,
Luke

**Comment by ccoughenour08** [comment]
@bitwalker - Good Morning, I got around to cleaning up the PR to remove the logger debugging. When the code for this PR is built out, the deploy (using CodeDeploy) fails with the following: 

LifecycleEvent - ApplicationStart
Script - bin/migrate
[stdout]
[stdout]23:58:15.229 [info] Application mix exited: :stopped
[stdout]==> Starting applications..
[stdout]==> Started crypto: [:crypto]
[stdout]==> Started ssl: [:asn1, :public_key, :ssl]
[stdout]==> Started postgrex: [:connection, :db_connection, :decimal, :postgrex]
[stdout]==> Started ecto: [:poison, :jason, :ecto]
[stdout]==> Started ecto_sql: [:telemetry, :ecto_sql]
[stdout]==> Starting repo
[stderr]** (EXIT from #PID<0.89.0>) an exception was raised:
**_[stderr] ** (ArgumentError) invalid :log configuration for Example.Repo, it should be false, :debug, :info, :warn or :error, got: true_**
[stderr] (ecto) lib/ecto/repo/supervisor.ex:53: Ecto.Repo.Supervisor.validate_config!/2
[stderr] (ecto) lib/ecto/repo/supervisor.ex:26: Ecto.Repo.Supervisor.runtime_config/4
[stderr] (ecto) lib/ecto/repo/supervisor.ex:187: Ecto.Repo.Supervisor.init/1

Would you be willing to take a look at the source and see if you can spot why this would be happening?

Thanks,
C Luke Coughenour

**Comment by bitwalker** [comment]
Ah, I bet that's Ecto being updated while an older `:logger` is used, or vice versa; #14 would definitely solve that, since it updates everything to be in sync. Have you given the master branch after that was merged a shot?

**Comment by ccoughenour08** [comment]
@bitwalker I will give a fresh branch a go this evening! Thank you for the community participation and response!

**Comment by ccoughenour08** [comment]
@bitwalker - The logger issue is fixed! Thank you. I am still seeing the 502 gateway error I was seeing when the deploy was failing:

image

Are you able to deploy the pipeline successfully and access the example application?

**Pull request closed without merging**
